export const actions = {
  FETCH_MEALTYPE_REQUEST: "FETCH_MEALTYPE_REQUEST",
  FETCH_MEALTYPE_SUCCESS: "FETCH_MEALTYPE_SUCCESS",
  FETCH_MEALTYPE_FAILURE: "FETCH_MEALTYPE_FAILURE",
};

export const restaurantsActions = {
  FETCH_RESTAURANTS_REQUEST: 'FETCH_RESTAURANTS_REQUEST',
  FETCH_RESTAURANTS_SUCCESS: 'FETCH_RESTAURANTS_SUCCESS',
  FETCH_RESTAURANTS_FAILURE: 'FETCH_RESTAURANTS_FAILURE',
}

export const menuItemsActions = {
  FETCH_MENUITEMS_REQUEST: 'FETCH_MENUITEMS_REQUEST',
  FETCH_MENUITEMS_SUCCESS: 'FETCH_MENUITEMS_SUCCESS',
  FETCH_MENUITEMS_FAILURE: 'FETCH_MENUITEMS_FAILURE',
}
