export const mealTypesActions = {
  FETCH_MEALTYPE_REQUEST: "FETCH_MEALTYPE_REQUEST",
  FETCH_MEALTYPE_SUCCESS: "FETCH_MEALTYPE_SUCCESS",
  FETCH_MEALTYPE_FAILURE: "FETCH_MEALTYPE_FAILURE",
};

export const restaurantDetailsActions = {
  FETCH_RESTAURANT_DETAILS_REQUEST: "FETCH_RESTAURANT_DETAILS_REQUEST",
  FETCH_RESTAURANT_DETAILS_SUCCESS: "FETCH_RESTAURANT_DETAILS_SUCCESS",
  FETCH_RESTAURANT_DETAILS_FAILURE: "FETCH_RESTAURANT_DETAILS_FAILURE",
};

export const menuItemsActions = {
  FETCH_MENUITEMS_REQUEST: "FETCH_MENUITEMS_REQUEST",
  FETCH_MENUITEMS_SUCCESS: "FETCH_MENUITEMS_SUCCESS",
  FETCH_MENUITEMS_FAILURE: "FETCH_MENUITEMS_FAILURE",
};

export const locationsActions = {
  FETCH_lOCATIONS_REQUEST: "FETCH_lOCATIONS_REQUEST",
  FETCH_lOCATIONS_SUCCESS: "FETCH_lOCATIONS_SUCCESS",
  FETCH_lOCATIONS_FAILURE: "FETCH_MENUITEMS_FAILURE",
};

export const restaurantsActions = {
  FETCH_RESTAURANTS_REQUEST: "FETCH_RESTAURANTS_REQUEST",
  FETCH_RESTAURANTS_SUCCESS: "FETCH_RESTAURANTS_SUCCESS",
  FETCH_RESTAURANTS_FAILURE: "FETCH_RESTAURANTS_FAILURE",
};
